### PR TITLE
Fix #140 fix Function _load_textdomain_just_in_time was called incorrectly.

### LINKED ISSUE #140: A notice is appearing in the debug log with WordPress version 6.8.0.
The notice is appearing without changing the site language.

Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the arconix-faq domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)

Image

### PR DESCRIPTION
**Pull request by gaminikhil**
Fix #140 fix Function _load_textdomain_just_in_time was called incorrectly.

### CODE REVIEW

File: includes/arconix-faq-all-component.php [hunk 1]
```diff
@@ -30,48 +30,53 @@ public function __construct() {
...
 
-				$ts_pro_faq = self::faq_get_faq();
-				new FAQ_TS_Faq_Support( $faq_plugin_name, $faq_plugin_prefix, $faq_plugins_page, $faq_locale, $faq_plugin_folder_name, $faq_plugin_slug, $ts_pro_faq, 'faq_support_page' );
-				if ( in_array( 'woocommerce/woocommerce.php', get_option( 'active_plugins' ) ) ) {
-					$ts_pro_notices = self::faq_get_notice_text();
-					new FAQ_ts_pro_notices( $faq_plugin_name, $faq_lite_plugin_prefix, $faq_plugin_prefix, $ts_pro_notices, $faq_file_name, $faq_pro_file_name );
-				}
+			$ts_pro_faq = self::faq_get_faq();
+			new FAQ_TS_Faq_Support( $faq_plugin_name, $faq_plugin_prefix, $faq_plugins_page, $faq_locale, $faq_plugin_folder_name, $faq_plugin_slug, $ts_pro_faq, 'faq_support_page' );
+			if ( in_array( 'woocommerce/woocommerce.php', get_option( 'active_plugins' ) ) ) { // phpcs:ignore
```
Comment (handelce) [inline includes/arconix-faq-all-component.php:77]: @gaminikhil Why are we using the PHPCS ignore here?

**Review by handelce — CHANGES_REQUESTED** [review]

**Review by rashmimalpande — APPROVED** [review]
